//! Explicit local SSH integration harness. The fake askpass is ONLY in this test binary.
//! Run with WCH_SSH_TEST_DIR pointing at fixtures generated by ssh_fixture.py.
#![allow(dead_code, unused_imports)]
#[path = "../src/foreground.rs"]
mod foreground;
#[path = "../src/remote.rs"]
mod remote;
#[path = "../src/remote_transport.rs"]
mod remote_transport;
#[path = "../src/ssh_auth.rs"]
mod ssh_auth;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().collect();
    let bridge = args.get(1).map(String::as_str) == Some("--ssh-askpass");
    if bridge || std::env::var_os("WSL_CLIPBOARD_ASKPASS").is_some() {
        if std::env::var_os("WCH_SSH_NATIVE_SMOKE").is_some() {
            std::process::exit(ssh_auth::handle_askpass().unwrap_or(1));
        }
        let (label, parent, silent) = if bridge {
            (args[3].clone(), args[5].clone(), args[6].clone())
        } else {
            (
                std::env::var("WSL_CLIPBOARD_AUTH_LABEL")?,
                std::env::var("WSL_CLIPBOARD_AUTH_PARENT")?,
                std::env::var("WSL_CLIPBOARD_AUTH_SILENT")?,
            )
        };
        if silent == "1" {
            std::process::exit(1);
        }
        use std::io::Write;
        let path = std::env::temp_dir().join(format!("wch-fixture-{parent}.prompts"));
        writeln!(
            std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(path)?,
            "{label}"
        )?;
        if label.contains("cancel") {
            std::process::exit(1);
        }
        // Fixed, disposable test credentials; never read real credentials from the user.
        println!(
            "{}",
            if label.contains("wrong") {
                "fixture-wrong"
            } else {
                "clipboard-fixture"
            }
        );
        return Ok(());
    }
    if std::env::var_os("WCH_SSH_NATIVE_SMOKE").is_some() {
        let auth = ssh_auth::Askpass::new("本机窗口测试（无需输入）".into(), false)?;
        let app = std::env::var_os("WCH_SSH_APP_EXE")
            .map(std::path::PathBuf::from)
            .unwrap_or(std::env::current_exe()?);
        let mut cmd = tokio::process::Command::new(app);
        cmd.arg("本机测试：窗口将自动关闭，请勿输入密码。")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .kill_on_drop(true)
            .creation_flags(0x08000000);
        auth.windows_env(&mut cmd);
        let mut child = cmd.spawn()?;
        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        anyhow::ensure!(
            child.try_wait()?.is_none(),
            "native dialog exited before cancellation"
        );
        drop(auth);
        let output =
            tokio::time::timeout(std::time::Duration::from_secs(3), child.wait_with_output())
                .await??;
        anyhow::ensure!(
            output.status.code() == Some(1),
            "cancelled native askpass must fail authentication"
        );
        anyhow::ensure!(
            output.stdout.is_empty(),
            "cancelled askpass must return no credential"
        );
        println!(
            "PASS native credential dialog: stayed open, cancelled by parent, no credential output"
        );
        return Ok(());
    }
    let Some(dir) = std::env::var_os("WCH_SSH_TEST_DIR") else {
        println!("SSH integration skipped (set WCH_SSH_TEST_DIR; see docs/ssh-auth-testing.md)");
        return Ok(());
    };
    remote::run_auth_fixture(std::path::Path::new(&dir)).await
}
